### ISSUE TITLE
parse error on execution

### ISSUE THREAD

**Issue by moogly81** [HeyWatch/webvtt-ruby#1]
Thanks for this tool ! I would really like to get it working , since it's exactly what I need. 
However, when I run the script , i get this error : 

[root@server] # webvtt-segmenter -i "subtitles/en.srt"  -t 10 -m "subtitles/en.m3u8" -o "subtitles/en-%05d.vtt"

Converting srt to webvtt format...
/usr/lib/ruby/gems/1.8/gems/webvtt-ruby-0.2.5/lib/parser.rb:127:in `parse': undefined method `include?' for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/gems/1.8/gems/webvtt-ruby-0.2.5/lib/parser.rb:87:in `initialize'
        from /usr/lib/ruby/gems/1.8/gems/webvtt-ruby-0.2.5/lib/parser.rb:73:in `new'
        from /usr/lib/ruby/gems/1.8/gems/webvtt-ruby-0.2.5/lib/parser.rb:73:in `parse'
        from /usr/lib/ruby/gems/1.8/gems/webvtt-ruby-0.2.5/lib/parser.rb:72:in `each'
        from /usr/lib/ruby/gems/1.8/gems/webvtt-ruby-0.2.5/lib/parser.rb:72:in `parse'
        from /usr/lib/ruby/gems/1.8/gems/webvtt-ruby-0.2.5/lib/parser.rb:38:in `initialize'
        from /usr/lib/ruby/gems/1.8/gems/webvtt-ruby-0.2.5/lib/parser.rb:23:in `new'
        from /usr/lib/ruby/gems/1.8/gems/webvtt-ruby-0.2.5/lib/parser.rb:23:in `convert_from_srt'
        from /usr/lib/ruby/gems/1.8/gems/webvtt-ruby-0.2.5/bin/webvtt-segmenter:48
        from /usr/bin/webvtt-segmenter:19:in `load'
        from /usr/bin/webvtt-segmenter:19

**Comment by sadikzzz** [comment]
Hi,

It seems there is a problem with the srt. Can you upload it somewhere?

**Comment by moogly81** [comment]
sure , here is it : 
https://drive.google.com/file/d/0B3k3ugpTh942RER1VEh1WFNmWGc/view?usp=sharing

**Comment by sadikzzz** [comment]
Hi,

The bug came from the empty lines at the end of your srt file. The parser didn't ignore them to convert it to vtt.
